version: "3.8"

services: 
  app:
    ## O "." indica que a imagem do Docker será construída no Diretório atual
    build: . 
    ## Acessa o shell do linux (/bin/sh)
    command: /bin/sh -c "npm install && npm start"
    ports:
    ## Mapeia a porta 5000 do container para a porta 5000 da máquina
      - "3000:3000"
    ## Monta o diretório atual da máquina host no diretório /usr/app dentro do container
    volumes:
      - .:/usr/app
      - /etc/letsencrypt:/etc/letsencrypt # Monta o volume dos certificados
    working_dir: /usr/app # Define o diretório de trabalho dentro do container
    ## Indica que o serviço app depende do serviço db
    depends_on:
      - db
  db:
    image: mysql:8.0
    ## Configura o container para reiniciar automaticamente caso ele pare
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_final
    ## Mapeia a porta 3306 do container para a porta 3306 da máquina
    ports:
      - "3308:3308"
    volumes: 
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data: