version: "3"

services:
  app:
    build: . # Usa o Dockerfile local para buildar a imagem
    command: /bin/sh -c "npm install && npm rebuild bcrypt --build-from-source && npm start"
    ports:
      - "3000:3000" # Mapeia a porta 5000 do container para a porta 3000 da máquina
    volumes:
      - .:/usr/app # Monta o diretório da máquina no container
      - /etc/letsencrypt:/etc/letsencrypt # Monta o volume dos certificados
    working_dir: /usr/app # Define o diretório de trabalho dentro do container
    depends_on:
      - db # O serviço app depende do serviço db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_final
    ports:
      - "3306:3307" # Corrigir para 3306:3307
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data: